const bancoDePreguntas = {
    facil: [
        // ─── FÁCIL: 50 preguntas ───────────────────────────────────────────────
        { "q": "¿Quién fue el primer hombre creado por Dios?", "o": ["Abel", "Caín", "Adán", "Set"], "c": 2 },
        { "q": "¿Cuántos días y noches llovió durante el diluvio?", "o": ["7", "40", "12", "100"], "c": 1 },
        { "q": "¿A quién entregó Dios los Diez Mandamientos?", "o": ["Abraham", "David", "Moisés", "Josué"], "c": 2 },
        { "q": "¿Qué joven derrotó al gigante Goliat con una honda?", "o": ["Salomón", "Saúl", "David", "Sansón"], "c": 2 },
        { "q": "¿Quién fue tragado por un gran pez por desobedecer a Dios?", "o": ["Pedro", "Jonás", "Noé", "Daniel"], "c": 1 },
        { "q": "¿En qué ciudad nació Jesús?", "o": ["Nazaret", "Jerusalén", "Belén", "Jericó"], "c": 2 },
        { "q": "¿Cuál es el primer libro de la Biblia?", "o": ["Éxodo", "Mateo", "Génesis", "Apocalipsis"], "c": 2 },
        { "q": "¿Quién construyó el arca para salvarse del diluvio?", "o": ["Moisés", "Abraham", "Noé", "Isaac"], "c": 2 },
        { "q": "¿Cuántos discípulos escogió Jesús originalmente?", "o": ["10", "12", "7", "3"], "c": 1 },
        { "q": "¿Quién fue vendido por sus hermanos como esclavo a Egipto?", "o": ["Benjamín", "José", "Judá", "Rubén"], "c": 1 },
        { "q": "¿Qué mar dividió Moisés para que pasara el pueblo?", "o": ["Mar Muerto", "Mar Rojo", "Mar de Galilea", "Mar Mediterráneo"], "c": 1 },
        { "q": "¿Cómo se llamaba la madre de Jesús?", "o": ["Marta", "Magdalena", "María", "Isabel"], "c": 2 },
        { "q": "¿Quién fue el hombre más fuerte de la Biblia?", "o": ["Sansón", "Goliat", "David", "Pedro"], "c": 0 },
        { "q": "¿Qué animal habló a Balaam?", "o": ["Una serpiente", "Un león", "Una asna", "Un cordero"], "c": 2 },
        { "q": "¿Quién fue el traidor que entregó a Jesús?", "o": ["Pedro", "Judas Iscariote", "Tomás", "Andrés"], "c": 1 },
        { "q": "¿De qué madera fue hecha el arca de Noé?", "o": ["Cedro", "Roble", "Gofre", "Pino"], "c": 2 },
        { "q": "¿Cuántos libros tiene la Biblia Reina Valera?", "o": ["66", "73", "50", "80"], "c": 0 },
        { "q": "¿Quién recibió una túnica de diversos colores de su padre?", "o": ["Isaac", "José", "David", "Salomón"], "c": 1 },
        { "q": "¿Qué mujer se convirtió en estatua de sal?", "o": ["La esposa de Abraham", "La esposa de Lot", "Eva", "Raquel"], "c": 1 },
        { "q": "¿Cuál es el último libro de la Biblia?", "o": ["Malaquías", "Judas", "Apocalipsis", "Juan"], "c": 2 },
        { "q": "¿Quién fue arrojado al foso de los leones?", "o": ["Daniel", "José", "Misael", "Esdras"], "c": 0 },
        { "q": "¿En qué día resucitó Jesús?", "o": ["El segundo día", "El séptimo día", "El tercer día", "El primer día"], "c": 2 },
        { "q": "¿Quién fue el primer rey de Israel?", "o": ["David", "Saúl", "Salomón", "Samuel"], "c": 1 },
        { "q": "¿Qué alimento cayó del cielo para los israelitas?", "o": ["Pan", "Codornices", "Maná", "Miel"], "c": 2 },
        { "q": "¿Cuántos años vivieron los israelitas en el desierto antes de entrar a Canaán?", "o": ["10 años", "20 años", "40 años", "70 años"], "c": 2 },
        { "q": "¿Cuántas plagas envió Dios a Egipto?", "o": ["7", "12", "10", "5"], "c": 2 },
        { "q": "¿Quién fue el padre de Isaac?", "o": ["Jacob", "Abraham", "Lot", "Noé"], "c": 1 },
        { "q": "¿Cómo se llamaba el hermano de Moisés?", "o": ["Aarón", "Josué", "Caleb", "Jetro"], "c": 0 },
        { "q": "¿Quién negó a Jesús tres veces?", "o": ["Judas", "Juan", "Pedro", "Tomás"], "c": 2 },
        { "q": "¿Cuál es el libro más largo de la Biblia?", "o": ["Génesis", "Isaías", "Salmos", "Jeremías"], "c": 2 },
        { "q": "¿Qué señal puso Dios para prometer que no habría otro diluvio?", "o": ["Una paloma", "Un arco iris", "Una nube", "Un olivo"], "c": 1 },
        { "q": "¿Quién bautizó a Jesús en el río Jordán?", "o": ["Pedro", "Juan el Bautista", "Pablo", "Santiago"], "c": 1 },
        { "q": "¿Qué ciudad fue destruida por sus muros al sonar las trompetas?", "o": ["Nínive", "Jericó", "Sodoma", "Babilonia"], "c": 1 },
        { "q": "¿Quién era el hijo de David que fue rey después de él?", "o": ["Absalón", "Adonías", "Salomón", "Natán"], "c": 2 },
        { "q": "¿Cuál fue el primer milagro de Jesús?", "o": ["Sanar a un ciego", "Caminar sobre el agua", "Convertir agua en vino", "Multiplicar los panes"], "c": 2 },
        { "q": "¿Cómo se llamaba la esposa de Abraham?", "o": ["Raquel", "Sara", "Rebeca", "Lea"], "c": 1 },
        { "q": "¿Quién fue el discípulo que dudó de la resurrección?", "o": ["Pedro", "Felipe", "Tomás", "Bartolomé"], "c": 2 },
        { "q": "¿Qué animal tentó a Eva en el Edén?", "o": ["Un león", "Una serpiente", "Un lobo", "Un mono"], "c": 1 },
        { "q": "¿Quién fue el hombre que vivió más años según la Biblia?", "o": ["Noé", "Matusalén", "Enoc", "Adán"], "c": 1 },
        { "q": "¿Cuántos hijos tuvo Jacob?", "o": ["10", "12", "7", "3"], "c": 1 },
        { "q": "¿A quién pidió Jesús que caminara sobre el agua?", "o": ["Juan", "Andrés", "Pedro", "Santiago"], "c": 2 },
        { "q": "¿Qué instrumento tocaba David?", "o": ["Flauta", "Trompeta", "Arpa", "Tambor"], "c": 2 },
        { "q": "¿Quién fue la mujer que engañó a Sansón?", "o": ["Dalila", "Rut", "Ester", "Jezabel"], "c": 0 },
        { "q": "¿Cuál era la profesión de Mateo antes de seguir a Jesús?", "o": ["Pescador", "Carpintero", "Publicano", "Pastor"], "c": 2 },
        { "q": "¿Quién escribió los Salmos en su mayoría?", "o": ["Moisés", "Salomón", "David", "Asaf"], "c": 2 },
        { "q": "¿Cómo se llamaba el jardín donde vivían Adán y Eva?", "o": ["Edén", "Getsemaní", "Sión", "Gólgota"], "c": 0 },
        { "q": "¿Qué le pidió Salomón a Dios?", "o": ["Riquezas", "Larga vida", "Sabiduría", "Victoria"], "c": 2 },
        { "q": "¿Cuál fue el primer acto profético registrado de Elías?", "o": ["Resucitar a un muerto", "Partir el río Jordán", "Anunciar que no llovería", "Llamar fuego del cielo"], "c": 2 },
        { "q": "¿Quién era el apóstol de los gentiles?", "o": ["Pedro", "Juan", "Pablo", "Mateo"], "c": 2 },
        { "q": "¿Qué significa 'Emmanuel'?", "o": ["Dios es amor", "Dios con nosotros", "Hijo de Dios", "Rey de Reyes"], "c": 1 }
    ],

    intermedio: [
        // ─── INTERMEDIO: 50 preguntas ──────────────────────────────────────────
        { "q": "¿Cómo se llamaba la madre de Samuel?", "o": ["Ana", "Penina", "Raquel", "Noemí"], "c": 0 },
        { "q": "¿Quién fue el sucesor del profeta Elías?", "o": ["Isaías", "Eliseo", "Jeremías", "Ezequiel"], "c": 1 },
        { "q": "¿En qué monte ofreció Abraham a su hijo Isaac?", "o": ["Sinaí", "Carmelo", "Moriah", "Horeb"], "c": 2 },
        { "q": "¿Quién era la suegra de Rut?", "o": ["Orfa", "Noemí", "Lea", "Isabel"], "c": 1 },
        { "q": "¿Cuál es el libro más corto del Antiguo Testamento?", "o": ["Abdías", "Hageo", "Nahúm", "Jonás"], "c": 0 },
        { "q": "¿Cuántos años reinó David en total?", "o": ["33 años", "40 años", "7 años", "50 años"], "c": 1 },
        { "q": "¿Quién fue el compañero de Pablo en su primer viaje misionero?", "o": ["Bernabé", "Silas", "Lucas", "Timoteo"], "c": 0 },
        { "q": "¿Qué profeta vio una visión de un valle de huesos secos?", "o": ["Isaías", "Jeremías", "Ezequiel", "Daniel"], "c": 2 },
        { "q": "¿Cómo se llamaba el padre de Juan el Bautista?", "o": ["José", "Zacarías", "Simeón", "Leví"], "c": 1 },
        { "q": "¿Quién era el rey de Babilonia cuando Jerusalén fue destruida?", "o": ["Ciro", "Darío", "Nabucodonosor", "Belsasar"], "c": 2 },
        { "q": "¿A qué apóstol se le conoce como 'el discípulo amado'?", "o": ["Pedro", "Santiago", "Juan", "Andrés"], "c": 2 },
        { "q": "¿Quién fue el juez que derrotó a los madianitas con solo 300 hombres?", "o": ["Gedeón", "Sansón", "Barac", "Jefté"], "c": 0 },
        { "q": "¿Cuál era el nombre judío de la reina Ester?", "o": ["Hadasa", "Rut", "Vasti", "Abigail"], "c": 0 },
        { "q": "¿Quién era el sumo sacerdote cuando nació Samuel?", "o": ["Aarón", "Elí", "Sadoc", "Abiatar"], "c": 1 },
        { "q": "¿En qué isla fue exiliado el apóstol Juan?", "o": ["Creta", "Chipre", "Patmos", "Malta"], "c": 2 },
        { "q": "¿Quién interpretó los sueños del Faraón en Egipto?", "o": ["Moisés", "José", "Daniel", "Nehemías"], "c": 1 },
        { "q": "¿Cuál fue el monte donde Elías desafió a los profetas de Baal?", "o": ["Sinaí", "Moriah", "Carmelo", "Hermón"], "c": 2 },
        { "q": "¿Quién escribió el libro de los Hechos?", "o": ["Pablo", "Mateo", "Lucas", "Pedro"], "c": 2 },
        { "q": "¿Cómo se llamaba la hermana de Moisés?", "o": ["Séfora", "María (Miriam)", "Débora", "Jael"], "c": 1 },
        { "q": "¿Qué rey de Judá vio retrasarse la sombra del reloj diez grados?", "o": ["Josías", "Ezequías", "Josafat", "Uzías"], "c": 1 },
        { "q": "¿Quién era el gobernador romano que condenó a Jesús?", "o": ["Herodes", "Félix", "Poncio Pilato", "Agripa"], "c": 2 },
        { "q": "¿Cuál fue el pecado de Ananías y Safira?", "o": ["Robo", "Mentir al Espíritu Santo", "Idolatría", "Adulterio"], "c": 1 },
        { "q": "¿Quién fue el primer mártir cristiano?", "o": ["Santiago", "Esteban", "Pedro", "Felipe"], "c": 1 },
        { "q": "¿A qué ciudad huía Jonás cuando se levantó la tempestad?", "o": ["Nínive", "Jope", "Tarsis", "Sidón"], "c": 2 },
        { "q": "¿Quién era el esposo de Débora, la jueza?", "o": ["Barac", "Lapidot", "Heber", "Sísara"], "c": 1 },
        { "q": "¿Qué mujer estéril hizo un voto a Dios en el tabernáculo y dio a luz al profeta Samuel?", "o": ["Sara", "Raquel", "Ana", "Mical"], "c": 2 },
        { "q": "¿Cuántas veces se menciona que Jesús lloró en los Evangelios?", "o": ["1 vez", "2 veces", "3 veces", "4 veces"], "c": 1 },
        { "q": "¿Quién era el compañero de Pablo en la cárcel de Filipos?", "o": ["Marcos", "Lucas", "Silas", "Timoteo"], "c": 2 },
        { "q": "¿En qué idioma se escribió originalmente el Nuevo Testamento?", "o": ["Hebreo", "Latín", "Griego", "Arameo"], "c": 2 },
        { "q": "¿Quién fue el profeta que ungió a Saúl y a David?", "o": ["Natán", "Samuel", "Elías", "Gad"], "c": 1 },
        { "q": "¿Cómo se llamaba el hijo primogénito de Isaac?", "o": ["Jacob", "Esaú", "Rubén", "José"], "c": 1 },
        { "q": "¿Cuántos años reinó Salomón sobre Israel?", "o": ["33 años", "40 años", "20 años", "50 años"], "c": 1 },
        { "q": "¿Quién era el padre de los apóstoles Santiago y Juan?", "o": ["Alfeo", "Zebedeo", "Jonás", "Cleofas"], "c": 1 },
        { "q": "¿Qué mujer ocultó a los espías en Jericó?", "o": ["Rut", "Rahab", "Débora", "Abigail"], "c": 1 },
        { "q": "¿Cuál era la tribu de la que provenía el apóstol Pablo?", "o": ["Judá", "Leví", "Benjamín", "Efraín"], "c": 2 },
        { "q": "¿Quién fue arrebatado al cielo en un torbellino?", "o": ["Moisés", "Enoc", "Elías", "Eliseo"], "c": 2 },
        { "q": "¿Cuántos días ayunó Jesús en el desierto?", "o": ["7 días", "12 días", "40 días", "3 días"], "c": 2 },
        { "q": "¿Quién era el hijo de Abraham y Agar?", "o": ["Isaac", "Ismael", "Jacob", "Esaú"], "c": 1 },
        { "q": "¿Qué profeta escribió sobre el 'siervo sufriente'?", "o": ["Isaías", "Jeremías", "Daniel", "Oseas"], "c": 0 },
        { "q": "¿Quién fue el discípulo que reemplazó a Judas Iscariote?", "o": ["Bernabé", "Matías", "Silas", "Esteban"], "c": 1 },
        { "q": "¿Cómo se llamaba el monte donde murió Moisés?", "o": ["Sinaí", "Nebo", "Ararat", "Carmelo"], "c": 1 },
        { "q": "¿Quién era el rey que quería matar al niño Jesús?", "o": ["Herodes el Grande", "Herodes Antipas", "Agripa", "César"], "c": 0 },
        { "q": "¿Qué apóstol era médico?", "o": ["Mateo", "Marcos", "Lucas", "Juan"], "c": 2 },
        { "q": "¿Cómo se llamaba la madre de Juan el Bautista?", "o": ["María", "Ana", "Isabel", "Salomé"], "c": 2 },
        { "q": "¿Quién era la madre de Timoteo?", "o": ["Loida", "Eunice", "Priscila", "Febe"], "c": 1 },
        { "q": "¿Qué milagro hizo Jesús en la casa de Jairo?", "o": ["Sanar un leproso", "Resucitar a su hija", "Convertir agua en vino", "Multiplicar peces"], "c": 1 },
        { "q": "¿Quién era el profeta que reprendió a David por su pecado?", "o": ["Samuel", "Natán", "Gad", "Elías"], "c": 1 },
        { "q": "¿A qué ciudad pertenecía la mujer samaritana?", "o": ["Siquem", "Sicar", "Samaria", "Nazaret"], "c": 1 },
        { "q": "¿Quién era el padre de Lot?", "o": ["Abraham", "Harán", "Nacor", "Taré"], "c": 1 },
        { "q": "¿En qué libro se encuentra la historia de la Torre de Babel?", "o": ["Éxodo", "Génesis", "Números", "Levítico"], "c": 1 }
    ],

    dificil: [
        // ─── DIFÍCIL: 50 preguntas ─────────────────────────────────────────────
        { "q": "¿Cuántos días reinó Zimri como rey de Israel antes de ser derrotado por Omri?", "o": ["3 días", "7 días", "14 días", "30 días"], "c": 1 },
        { "q": "¿Quién fue el padre de Bezaleel, el constructor del Tabernáculo?", "o": ["Uri", "Hur", "Caleb", "Aarón"], "c": 0 },
        { "q": "¿Cuántos años tenía Josías cuando comenzó a reinar?", "o": ["7 años", "8 años", "12 años", "16 años"], "c": 1 },
        { "q": "¿Quién fue el tercer hijo de Adán y Eva?", "o": ["Abel", "Set", "Enoc", "Jared"], "c": 1 },
        { "q": "¿Cuántos años tenía Josué cuando murió, según el libro de Josué?", "o": ["100 años", "110 años", "120 años", "90 años"], "c": 1 },
        { "q": "¿Cómo se llamaba el sirviente de Abraham enviado a buscar esposa para Isaac?", "o": ["Eliezer", "Gueazi", "Abisai", "Ittai"], "c": 0 },
        { "q": "¿Quién fue el primer juez de Israel?", "o": ["Otoniel", "Ehud", "Samgar", "Gedeón"], "c": 0 },
        { "q": "¿En qué libro se menciona la guerra en el cielo entre Miguel y el dragón?", "o": ["Daniel", "Ezequiel", "Judas", "Apocalipsis"], "c": 3 },
        { "q": "¿Cómo se llamaba el padre del rey Saúl?", "o": ["Abner", "Quis", "Ner", "Abiel"], "c": 1 },
        { "q": "¿Cuál de estos no era uno de los tres amigos originales de Job?", "o": ["Elifaz", "Bildad", "Zofar", "Eliú"], "c": 3 },
        { "q": "¿Quién fue el hijo de Moisés nacido en Madián?", "o": ["Gerson", "Eliezer", "Finees", "Eleazar"], "c": 0 },
        { "q": "¿Cómo se llamaba el rey de Moab que contrató a Balaam?", "o": ["Balac", "Eglón", "Mesha", "Sijón"], "c": 0 },
        { "q": "¿En qué lugar murió el sumo sacerdote Aarón?", "o": ["Monte Sinaí", "Monte Hor", "Monte Nebo", "Monte Carmelo"], "c": 1 },
        { "q": "¿Quién fue el padre de Josué?", "o": ["Nun", "Caleb", "Efraín", "Jetro"], "c": 0 },
        { "q": "¿Qué nombre puso Jacob al lugar donde luchó con el ángel?", "o": ["Betel", "Peniel", "Mahanaim", "Sucot"], "c": 1 },
        { "q": "¿Cuántos años tenía Abraham cuando nació Isaac?", "o": ["75 años", "90 años", "100 años", "120 años"], "c": 2 },
        { "q": "¿Quién fue la madre de Salomón?", "o": ["Mical", "Betsabé", "Abigail", "Ahinoam"], "c": 1 },
        { "q": "¿Qué profeta describe una visión de carros de fuego alrededor de una ciudad?", "o": ["Elías", "Eliseo", "Miqueas", "Zacarías"], "c": 1 },
        { "q": "¿Cómo se llamaba el escriba de Jeremías?", "o": ["Baruc", "Seraías", "Sedequías", "Hilquías"], "c": 0 },
        { "q": "¿Cuál era el nombre del monte donde encalló el arca de Noé?", "o": ["Ararat", "Sinaí", "Carmelo", "Hermón"], "c": 0 },
        { "q": "¿Quién fue el rey de Judá que fue llevado ciego a Babilonia?", "o": ["Joacín", "Joaquín", "Sedequías", "Manasés"], "c": 2 },
        { "q": "¿Cómo se llamaba la madre de los apóstoles Santiago y Juan, que pidió puestos de honor para sus hijos ante Jesús?", "o": ["María Magdalena", "Salomé", "María de Cleofas", "Juana"], "c": 1 },
        { "q": "¿Qué nombre significa 'Padre de una multitud'?", "o": ["Abraham", "Abram", "Israel", "Isaac"], "c": 0 },
        { "q": "¿Quién mató a 600 filisteos con una aguijada de bueyes?", "o": ["Ehud", "Samgar", "Gedeón", "Otoniel"], "c": 1 },
        { "q": "¿Cómo se llamaba la esposa de Moisés?", "o": ["Séfora", "Miriam", "Jael", "Débora"], "c": 0 },
        { "q": "¿Quién era el rey de Salem y sacerdote del Dios Altísimo?", "o": ["Abimelec", "Melquisedec", "Jetro", "Esdras"], "c": 1 },
        { "q": "¿En qué libro se encuentra el cántico de Débora?", "o": ["Éxodo", "Jueces", "Samuel", "Salmos"], "c": 1 },
        { "q": "¿Quién fue el padre de Matusalén?", "o": ["Enoc", "Jared", "Lamec", "Mahalalel"], "c": 0 },
        { "q": "¿Cuál era la ciudad natal del profeta Amós?", "o": ["Tecoa", "Anatot", "Tisbe", "Moreset"], "c": 0 },
        { "q": "¿Quién fue el sucesor de Salomón como rey de Israel?", "o": ["Jeroboam", "Roboam", "Abías", "Asa"], "c": 1 },
        { "q": "¿Cómo se llamaba el general del ejército de Jabín que Débora derrotó?", "o": ["Sísara", "Barac", "Og", "Sijón"], "c": 0 },
        { "q": "¿Cuántos años tenía Moisés cuando murió?", "o": ["80 años", "100 años", "120 años", "110 años"], "c": 2 },
        { "q": "¿Quién era el sumo sacerdote que ayudó a Esdras en la restauración?", "o": ["Josué", "Eliasib", "Hilquías", "Azarías"], "c": 1 },
        { "q": "¿Cómo se llamaba el primer hijo de José nacido en Egipto?", "o": ["Efraín", "Manasés", "Benjamín", "Gerson"], "c": 1 },
        { "q": "¿Qué profeta fue llevado a Babilonia en la primera deportación?", "o": ["Ezequiel", "Daniel", "Jeremías", "Habacuc"], "c": 1 },
        { "q": "¿Quién fue el padre de Noé?", "o": ["Lamec", "Matusalén", "Enoc", "Jared"], "c": 0 },
        { "q": "¿Cómo se llamaba el lugar donde los israelitas hallaron aguas amargas?", "o": ["Elim", "Mara", "Refidim", "Meriba"], "c": 1 },
        { "q": "¿Quién fue el rey que vio la escritura en la pared durante un banquete?", "o": ["Belsasar", "Nabucodonosor", "Darío", "Ciro"], "c": 0 },
        { "q": "¿En qué libro se describe la visión de las 70 semanas?", "o": ["Ezequiel", "Zacarías", "Daniel", "Apocalipsis"], "c": 2 },
        { "q": "¿Cómo se llamaba el padre de David?", "o": ["Isaí (Jesé)", "Saúl", "Booz", "Obed"], "c": 0 },
        { "q": "¿Quién fue el hijo de Jacob que propuso no matar a José sino arrojarlo al pozo?", "o": ["Judá", "Rubén", "Simeón", "Leví"], "c": 1 },
        { "q": "¿Cuál es el nombre del lugar donde Abraham compró una cueva para sepultura?", "o": ["Macpela", "Siquem", "Hebrón", "Moriah"], "c": 0 },
        { "q": "¿Quién fue el profeta que llamó fuego del cielo sobre los soldados del rey Ocozías?", "o": ["Eliseo", "Elías", "Samuel", "Isaías"], "c": 1 },
        { "q": "¿Cómo se llamaba la madre amonita de Roboam, el hijo que sucedió a Salomón?", "o": ["Betsabé", "Naama", "Abigaíl", "Mical"], "c": 1 },
        { "q": "¿Qué rey de Judá destruyó la serpiente de bronce que había hecho Moisés?", "o": ["Josías", "Ezequías", "Uzías", "Asa"], "c": 1 },
        { "q": "¿Cuál era el lugar que David ocupaba entre sus hermanos?", "o": ["El mayor", "El segundo", "El tercero", "El menor"], "c": 3 },
        { "q": "¿Quién fue el autor del libro de Lamentaciones según la tradición?", "o": ["Isaías", "Jeremías", "Ezequiel", "Baruc"], "c": 1 },
        { "q": "¿Cómo se llamaba el oficial etíope que Felipe bautizó en el camino a Gaza?", "o": ["Ebed-melec", "Candace", "No se menciona su nombre", "Simeón el negro"], "c": 2 },
        { "q": "¿Quién fue el padre de Samuel?", "o": ["Elcana", "Elí", "Leví", "Coré"], "c": 0 },
        { "q": "¿En qué ciudad se encontraban los creyentes cuando fueron llamados cristianos por primera vez?", "o": ["Jerusalén", "Antioquía", "Damasco", "Roma"], "c": 1 }
    ]
};